app:
  myport: ${PORT:0}
server:
  port: ${app.myport}
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: newsapi.noreply@gmail.com
    password: stwfmclgegfgfcck
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:notification
    username: sa
    password: 123456
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  application:
    name: notification-service
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
