spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter
        - id: chefes
          uri: lb://CHEFE-SERVICE
          predicates:
            - Path=/chefe/**
          filters:
            - AuthenticationFilter
        - id: ingredientes
          uri: lb://INGREDIENTE-SERVICE
          predicates:
            - Path=/ingrediente/**
          filters:
            - AuthenticationFilter
        - id: notifications
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/email/**
          filters:
            - AuthenticationFilter
        - id: receitas
          uri: lb://RECEITA-SERVICE
          predicates:
            - Path=/receita/**
          filters:
            - AuthenticationFilter
        - id: usuarios
          uri: lb://USUARIO-SERVICE
          predicates:
            - Path=/usuarios/**
          filters:
            - AuthenticationFilter

  application:
    name: gateway-service
server:
  port: 9999
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      #defaultZone: http://EUREKA-SERVER:8761/eureka
jwt:
  secret: 1f8be7b4f208b9189f939691a227fc5abe4ecbd938628d1e82cd3bc1bf4e75ab