services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: RABBIT-SERVER
    networks:
      - cookease-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
  eureka-service:
    build:
      context: ../eureka-service/docker
      dockerfile: Dockerfile
    container_name: EUREKA-SERVER
    image: joaofigueredo/eureka-service:latest
    ports:
      - "8761:8761"
    networks:
      - cookease-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
  chefe-service:
    build:
      context: ../chefe-service/docker
      dockerfile: Dockerfile
    image: joaofigueredo/chefe-service:latest
    networks:
      - cookease-network
    environment:
      EUREKA_SERVER_URL: http://eureka-service:8761/eureka/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - eureka-service
  #      - mysql-cookease-network
  ingrediente-service:
    build:
      context: ../ingrediente-service/docker
      dockerfile: Dockerfile
    image: joaofigueredo/ingrediente-service:latest
    networks:
      -  cookease-network
    environment:
      EUREKA_SERVER_URL: http://eureka-service:8761/eureka/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - eureka-service
#    deploy:
#      replicas: 3
  receita-service:
    build:
      context: ../receita-service/docker
      dockerfile: Dockerfile
    image: joaofigueredo/receita-service:latest
    networks:
      - cookease-network
    environment:
      EUREKA_SERVER_URL: http://eureka-service:8761/eureka/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - eureka-service
#    deploy:
#      replicas: 5
  notification-service:
    build:
      context: ../notification-service/docker
      dockerfile: Dockerfile
    image: joaofigueredo/notification-service:latest
    networks:
      - cookease-network
    environment:
      EUREKA_SERVER_URL: http://eureka-service:8761/eureka/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - eureka-service
      - usuario-service
#    deploy:
#      replicas: 10
  usuario-service:
    build:
      context: ../usuario-service/docker
      dockerfile: Dockerfile
    image: joaofigueredo/usuario-service:latest
    networks:
      - cookease-network
    environment:
      EUREKA_SERVER_URL: http://eureka-service:8761/eureka/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - eureka-service
  auth-service:
    build:
      context: ../auth-service/docker
      dockerfile: Dockerfile
    image: joaofigueredo/auth-service:latest
    networks:
      - cookease-network
    environment:
      EUREKA_SERVER_URL: http://eureka-service:8761/eureka/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - eureka-service
      - usuario-service
  gateway:
    build:
      context: ../gateway/docker
      dockerfile: Dockerfile
    image: joaofigueredo/gateway:latest
    ports:
      - "8080:8080"
    networks:
      - cookease-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - eureka-service
      - auth-service
      - chefe-service
      - ingrediente-service
      - notification-service
      - receita-service
      - usuario-service
networks:
  cookease-network:
    driver: bridge